config/routes.rb
Rails.application.routes.draw do
  get '/users/sign_up', to: 'trips#index'
  devise_for :users, path_names: {sign_in: 'login',
                                  sign_out: 'logout'}

  authenticate :user do
    root to: 'trips#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      collection { post :import }
      collection { delete :destroy_all_guardians }
    end

    resources :participants, only: [:index] do
      collection { post :import }
    end

    delete '/destroy_all_participants',
      to: 'participants#destroy_all_participants'

    resources :trips
  end
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id         :integer          not null, primary key
#  title      :string
#  location   :string
#  seats      :integer
#  alt_seats  :integer
#  start_date :date
#  start_time :time
#  end_time   :time
#  published  :boolean          default("false")
#

class Trip < ActiveRecord::Base
  MAX_SEATS = 60
  MAX_ALT_SEATS = 30

  has_many :participant_trips
  has_many :participants, through: :participant_trips

  validates :title, presence: true
  validates :alt_seats, presence: true
  validates :seats, presence: true
  validates :start_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  scope :published, -> { where(published: true) }

  def self.max_seats
    (1..MAX_SEATS).to_a
  end

  def self.max_alt_seats
    (1..MAX_ALT_SEATS).to_a
  end

  def seats_left
    count = participant_trips.where(primary: true).count
    seats - count
  end

  def alt_seats_left
    count = participant_trips.where(primary: false).count
    alt_seats - count
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @trips = Trip.all
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)

    if @trip.save
      flash[:notice] = "#{trip_params[:title]} has been added."
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      flash[:notice] = "#{trip_params[:title]} has been updated"
      redirect_to trips_path
    else
      render :edit
    end
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.participants.each { |participant| participant.destroy }
    trip.destroy
    flash[:notice] = "#{trip.title} was removed."
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:title,
      :location, :seats, :alt_seats, :published,
      :start_date, :start_time, :end_time)
  end
end

app/views/trips/_form.html.haml
.card
  .card-header
    = @trip.new_record? ? 'New Trip' : 'Update Trip'
  .card-block
    = form_for @trip do |f|
      - if @trip.errors.any?
        = render '/shared/errors', errors: @trip.errors
      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control"

      .form-group
        = f.label :seats
        = f.select :seats, Trip.max_seats, {}, {class: 'form-control'}

      .form-group
        = f.label :alt_seats, 'Alternate Seats'
        = f.select :alt_seats, Trip.max_alt_seats, {}, {class: 'form-control'}

      .form-group
        = f.label :start_date
        = f.date_field :start_date, class: 'form-control', value: Date.today

      .form-group
        = f.label :start_time
        = f.time_field :start_time, class: 'form-control'

      .form-group
        = f.label :end_time
        = f.time_field :end_time, class: 'form-control'

      .form-check
        = f.label :published, class: 'form-check-label' do
          = f.check_box :published, class: 'form-check-input'
          publish

      - button_text = @trip.new_record? ? 'Create' : 'Update'
      = f.submit button_text, class: 'btn btn-primary'

app/views/trips/edit.html.haml
= render 'form'

app/views/trips/index.html.haml
.card
  .card-block
    .card-title
      Trips
    %table.table
      %thead.thead-inverse
        %tr
          %th
          %th
          %th Title
          %th Start Date
          %th Start Time
          %th End Time
          %th Seats
          %th Alt Seats
          %th Published
      %tbody
        - @trips.each do |trip|
          %tr
            %td= link_to icon('pencil'), edit_trip_path(trip)
            %td= link_to icon('trash-o'), trip_path(trip), method: :delete
            %td= link_to trip.title, trip_path(trip)
            %td= trip.start_date
            %td= trip.start_time
            %td= trip.end_time
            %td.text-center= trip.seats
            %td.text-center= trip.alt_seats
            %td.text-center= trip.published? ? 'yes' : 'no'

app/views/trips/new.html.haml
.card
  .card-header
    New Trip
  .card-block
    = form_for @trip do |f|
      - if @trip.errors.any?
        = render '/shared/errors', errors: @trip.errors
      .form-group
        = f.label :title
        = f.text_field :title, class: "form-control"

      .form-group
        = f.label :seats
        = f.select :seats, Trip.max_seats, {}, {class: 'form-control'}

      .form-group
        = f.label :alt_seats, 'Alternate Seats'
        = f.select :alt_seats, Trip.max_alt_seats, {}, {class: 'form-control'}

      .form-group
        = f.label :start_date
        = f.date_field :start_date, class: 'form-control', value: Date.today

      .form-group
        = f.label :start_time
        = f.time_field :start_time, class: 'form-control'

      .form-group
        = f.label :end_time
        = f.time_field :end_time, class: 'form-control'

      .form-check
        = f.label :published, class: 'form-check-label' do
          = f.check_box :published, class: 'form-check-input'
          publish

      = f.submit 'Create', class: 'btn btn-primary'

app/views/trips/show.html.haml
.card
  .card-header
    Trip Info
    %span
      |
      seats:
      = @trip.seats
      \\
      = @trip.seats_left
    %span
      |
      alternate seats:
      = @trip.alt_seats
    %div
      = link_to 'edit', edit_trip_path(@trip)
  .card-block
    %h4.card-title= @trip.title
    %h6.card-subtitle.text-muted= @trip.start_date

    - @trip.participants.each do |kid|
      %div= kid.first_name