config/routes.rb
Rails.application.routes.draw do
  get '/users/sign_up', to: 'trips#index'
  devise_for :users, path_names: {sign_in: 'login',
                                  sign_out: 'logout'}

  authenticate :user do
    root to: 'trips#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :users do
      collection { post :import }
      collection { delete :destroy_all_guardians }
    end

    resources :participants, only: [:index] do
      collection { post :import }
    end

    delete '/destroy_all_participants',
      to: 'participants#destroy_all_participants'

    resources :trips
  end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_sym == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BgcAdmin
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %div.container
      - if user_signed_in?
        Logged in as
        %strong= current_user.email
        = link_to 'Edit profile |', edit_user_registration_path
        = link_to 'Logout |', destroy_user_session_path, method: :delete
        = link_to 'Trips', trips_path

        - if current_user.admin?
          = link_to ' | Guardians', users_path
          = link_to ' | Participants', participants_path
          = link_to ' | Create Trip', new_trip_path
      - else
        = link_to 'Log in', new_user_session_path

      = render 'layouts/messages'

      = yield